### ISSUE TITLE
Display line number in code block

### ISSUE THREAD

**Issue by javamonkey** [actframework/act-dockit#14]
For a given code block like:

``` java
  int a = 1;
  int a = 2;
```

It suggests to add line numbers in the rendered result:

``` java
1 int a = 1;
2 int b = 2;
```

Or if it can specify the start number ,it would be great:

``````
```java,number_start=23
int a = 1;
int b = 2;
``````

renders the following result:

``` java
23 int a = 1;
24 int b = 2;
```

**Comment by greenlaw110** [comment]
Done! see:

![image](https://cloud.githubusercontent.com/assets/216930/15448471/0c07148a-1fa6-11e6-8b36-3c71261ed900.png)
